# define parameters for calibration and identification process
# robot: soarm
---
calibration:
  calib_level: full_params # full_params /joint_offset
  non_geom: False
  base_frame: Base # start_frame of kinematic chain
  tool_frame: end_effector # end_frame of kinematic chain
  base_to_ref_frame:  # camera frame
  ref_frame:  # parent joint frame of camera frame
  markers:
    - ref_joint: 6 # joint index of parent joint of camera frame
      measure:  [True, True, True, False, False, False]
  free_flyer: False
  camera_pose: [0., 0.0, 0.0, 0, 0.0, 0.]
  tip_pose: [0, 0, 0, 0, 0, 0]
  coeff_regularize: 0.000
  outlier_eps: 0.15 #meter
  data_file: data/transformed_poses.csv
  sample_configs_file: data/optimal_configs/eye_hand_calibration_tiago_hey5_100.yaml
  nb_sample: 100
...
